<a href="https://colab.research.google.com/github/NehalShahu/NNDL_practicals/blob/main/NNDL_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
A = np.array([[2,3],[4,4]])
B = np.array([[4,5],[6,7]])
C = A+B
print("Matrix addition:\n",C)

A = np.array([[2,3],[4,4]])
B = np.array([[4,5],[6,7]])
C = np.matmul(A,B)
print("Matrix multiplication:\n",C)

A = np.array([[2,3],[4,4]])
B = np.array([[4,5],[6,7]])
C = np.array([[3,8],[4,2]])
D = np.matmul(A,B,C)
print("Matrix multiplication:\n",D)

A = np.array([[2,3,1],[4,4,2],[2,5,8]])
B = np.array([[4,5,8],[6,7,1],[2,9,8]])
C = np.array([[3,8,2],[4,2,5],[9,1,3]])
D = np.matmul(A,B,C)
print("Matrix multiplication:\n",D)

Matrix addition:
 [[ 6  8]
 [10 11]]
Matrix multiplication:
 [[26 31]
 [40 48]]
Matrix multiplication:
 [[26 31]
 [40 48]]
Matrix multiplication:
 [[ 28  40  27]
 [ 44  66  52]
 [ 54 117  85]]
